version: '3.1'

services:
  card-service:
    build:
      context: ../
      dockerfile: ./docker/dockerfile
      args:
        PROJECT_NAME: card-micro-service
    networks:
      - card-store-net
      - card-db-net
      - proxy-web
    depends_on:
      - db-card
    environment:
      SPRING_PROFILES_ACTIVE: docker

  front:
    build: ../front
    environment:
      REACT_APP_NOTIFICATION_SOCKET_URL: ws://localhost:80/notification-service/socket
    networks:
      - proxy-web
    ports:
      - "8080:80"

  proxy-reverse:
    image: nginx:1.25.0-alpine3.17
    networks:
      - proxy-web
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - user-service
      - card-service
      - store-service
      - authentication-service

  esb:
    image: symptoma/activemq:latest
    ports:
      - "61616:61616"
      - "61613:61613"
      - "8161:8161"
    networks:
      - esb
    environment:
      ACTIVEMQ_DISALLOW_WEBCONSOLE: false
      ACTIVEMQ_USERNAME: myuser
      ACTIVEMQ_PASSWORD: mypwd
      ACTIVEMQ_WEBADMIN_USERNAME: myuserweb
      ACTIVEMQ_WEBADMIN_PASSWORD: mypwd

  user-service:
    build:
      context: ../
      dockerfile: ./docker/dockerfile
      args:
        PROJECT_NAME: user-micro-service
    networks:
      - user-store-net
      - user-db-net
      - proxy-web
    depends_on:
      - db-user
      - card-service
    environment:
      SPRING_PROFILES_ACTIVE: docker

  authentication-service:
    build:
      context: ../
      dockerfile: ./docker/dockerfile
      args:
        PROJECT_NAME: authentication-micro-service
    networks:
      - user-store-net
      - proxy-web
    depends_on:
      - user-service
    environment:
      SPRING_PROFILES_ACTIVE: docker

  store-service:
    build:
      context: ../
      dockerfile: ./docker/dockerfile
      args:
        PROJECT_NAME: store-micro-service
    networks:
      - card-store-net
      - user-store-net
      - store-db-net
      - proxy-web
    depends_on:
      - card-service
      - db-store
    environment:
      SPRING_PROFILES_ACTIVE: docker


  db-user:
    image: postgres
    restart: always
    volumes:
      - db-user:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: app
    networks:
      - user-db-net
    ports:
      - "5438:5432"

  db-card:
    image: postgres
    restart: always
    volumes:
      - db-card:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: app
    networks:
      - card-db-net
    ports:
      - "5439:5432"

  db-store:
    networks:
      - store-db-net
    image: postgres
    restart: always
    volumes:
      - db-store:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: app
    ports:
      - "5434:5432"

networks:
  user-db-net:
  user-store-net:
  card-db-net:
  card-store-net:
  store-db-net:
  proxy-web:
  esb:

volumes:
  db-user:
  db-card:
  db-store:
