FROM openjdk:17-jdk-slim

ARG PROJECT_NAME

WORKDIR /usr/local/lib/

COPY ./common/target/*.jar ./app.jar
COPY ./${PROJECT_NAME}/target/classes .
ENTRYPOINT ["java","-jar","/usr/local/lib/app.jar", "--spring.profiles.active=docker", "--classpath /usr/local/lib/classes"]