server.port: 80
spring:
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    generate-ddl: true
  datasource:
    url: jdbc:postgresql://db-card:5432/app
    password: mypassword
    username: myuser

